#!/usr/bin/zsh

echo "Pulling dotfiles"
cd /home/angus/dotfiles/ && git pull 
cd /home/angus

echo ""
echo "Pulling neovim config"
cd /home/angus/.config/nvim/ && git pull 
cd /home/angus

echo ""
echo "Pulling scripts"
cd /home/angus/scripts && git pull 
cd /home/angus

echo ""
echo "Pulling latex stuff"
cd /home/angus/latex/homework/ && git pull 
cd /home/angus
cd /home/angus/latex/notes-private/ && git pull 
cd /home/angus
cd /home/angus/latex/notes-public/ && git pull 
cd /home/angus
