#!/usr/bin/python3
import os
import argparse as ap
import subprocess as sp
import sys

SERVER = "angus@angus-server.duckdns.org"
COMMAND = "latexmk -pdf -interaction=nonstopmode -synctex=1 -verbose"

parser = ap.ArgumentParser(description="Compile file.tex on angus-server")
parser.add_argument(metavar='/path/to/file.tex', \
        dest='filepath', \
        type=str, \
        help="Absolute path to file.tex to be compiled")

args = parser.parse_args()
path = args.filepath

folder, filename = os.path.split(path)
filenamenoextension, extension = os.path.splitext(filename)
top_folder = os.path.split(folder)[1]

if not os.path.isfile(path):
    print(path + " does not exist.")
    sys.exit(1)
elif not os.path.isabs(path):
    print(path + " is not absolute.")
    sys.exit(1)
elif not extension == '.tex':
    print(path + " does not have .tex extension.")
    sys.exit(1)

print("Syncing " + folder + " to " + SERVER + "...")
forward_sync = sp.run("rsync -a -h --delete --exclude=\".[!.]*\" --info=progress2 " + folder + " " + SERVER + ":/tmp/", shell=True)

if forward_sync.returncode != 0:
    print("Forward rsync finished with nonzero exit code. Exiting.")
    sys.exit(1)

ssh_command = "ssh " + SERVER + " \"" + "cd /tmp/" + top_folder + " && " + COMMAND + " " + filename + "\""

print("Success! Running command:")
print("    " + ssh_command)
print("----- latexmk output begins here -----")
latexmk_run = sp.run(ssh_command, shell=True)
print("----- latexmk output ends here -----")

if latexmk_run.returncode != 0:
    print("Server-side latexmk run finished with nonzero exit code. Not syncing back.")
    sys.exit(1)
else:
    print:("latexmk run successful! Syncing back...")

rsync_back = sp.run("rsync -a -h --exclude=\".[!.]*\" --info=progress2 " + SERVER + ":/tmp/" + top_folder + "/ " + folder + "/", shell=True)

if rsync_back.returncode != 0:
    print("Rsync back failed for some reason.")
    sys.exit(1)
else:
    print("Synced back succesfully!")

print("Fiddling with " + filenamenoextension + ".synctex.gz to make synctex work...")
sp.run("yes | gzip -f -d " + filenamenoextension + ".synctex.gz", shell=True)
sp.run("sed -i -e 's/\/tmp/\.\./' " + filenamenoextension + ".synctex", shell=True)
sp.run("gzip " + filenamenoextension + ".synctex", shell=True)
print("Done! Exiting :)")
