#!/bin/bash

xinput=$(xinput | grep TouchPad)
[[ $xinput =~ id=([0-9]+) ]]
padID="${BASH_REMATCH[1]}"

listProps=$(xinput list-props $padID | grep "Device Enabled")
[[ $listProps =~ [0-1]$ ]]
enabled="${BASH_REMATCH[0]}"

if [ $enabled -eq 1 ]
then
        xinput set-prop $padID "Device Enabled" 0
else
        xinput set-prop $padID "Device Enabled" 1
fi
