#!/bin/bash

currentbrightness=$(cat /sys/class/backlight/intel_backlight/brightness)
maxbrightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

if [ $currentbrightness -eq "1" ]
then xbright =400
else xbright =1 
fi

